apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratabench
resources:
  - namespace.yaml
  - pvc.yaml
  - crd-benchmark.yaml
  - api-deployment.yaml
  - agent-daemonset.yaml
  - cronjob-nvme.yaml
  - example-benchmark.yaml
