package lab

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
)

// EnsureCredentials fills S3 keys if using defaults.
func EnsureCredentials(cfg *Config) error {
	if cfg.S3.AccessKey != "" && cfg.S3.AccessKey != "minioadmin" {
		return nil
	}
	if cfg.S3.SecretKey != "" && cfg.S3.SecretKey != "minioadmin" {
		return nil
	}
	// Keep minioadmin for lab unless user wants generated
	if os.Getenv("LAB_GENERATE_CREDENTIALS") == "1" {
		sk, err := randomHex(16)
		if err != nil {
			return err
		}
		cfg.S3.AccessKey = "stratabench"
		cfg.S3.SecretKey = sk
	}
	return nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// WriteEnvFile writes a lab.env for shell scripts.
func WriteEnvFile(path string, cfg Config) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by stratabench lab\n")
	fmt.Fprintf(&b, "LAB_SSH_USER=%s\n", cfg.SSH.User)
	if cfg.SSH.Key != "" {
		fmt.Fprintf(&b, "LAB_SSH_KEY=%s\n", cfg.SSH.Key)
	}
	fmt.Fprintf(&b, "INSTALL_DIR=%s\n", cfg.InstallDir)
	fmt.Fprintf(&b, "LAB_AGENT_PORT=%d\n", cfg.AgentPort)
	fmt.Fprintf(&b, "LAB_CLIENT_HOSTS=%s\n", strings.Join(cfg.ClientHosts(), ","))
	fmt.Fprintf(&b, "LAB_S3_ENDPOINTS=%s\n", cfg.ServerCSV())
	fmt.Fprintf(&b, "WARP_ACCESS_KEY=%s\n", cfg.S3.AccessKey)
	fmt.Fprintf(&b, "WARP_SECRET_KEY=%s\n", cfg.S3.SecretKey)
	fmt.Fprintf(&b, "WARP_VERSION=%s\n", cfg.Tools.WarpVersion)
	fmt.Fprintf(&b, "LAB_PROFILE=%s\n", cfg.DefaultRun.Profile)
	fmt.Fprintf(&b, "LAB_TOPOLOGY=%s\n", cfg.DefaultRun.Topology)
	return os.WriteFile(path, []byte(b.String()), 0o600)
}
